# Melt

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("./data/ny_county_pop.csv")

df

                 county gender   child   adult  senior
0         Albany County      M   29296   99324   24568
1         Albany County      F   28137  102485   31564
2       Allegany County      M    4803   14536    4526
3       Allegany County      F    4541   13868    4753
4          Bronx County      M  177091  414274   79363
..                  ...    ...     ...     ...     ...
119  Westchester County      F  104119  306495  100289
120      Wyoming County      M    3667   13857    3905
121      Wyoming County      F    3810   10710    4031
122        Yates County      M    2810    6658    2616
123        Yates County      F    2816    6961    2776

[124 rows x 5 columns]

## Basic melting

Goal: make this dataframe a long table, in other words, having one column with values instead of three.

- `id_vars`: columns to keep fixed
- Everything else becomes long format

In [2]:
melt_df = df.melt(id_vars=["county", "gender"],
                  value_vars=['child', 'adult', 'senior'],
                  var_name="age_group", value_name='population')

melt_df

                 county gender age_group  population
0         Albany County      M     child       29296
1         Albany County      F     child       28137
2       Allegany County      M     child        4803
3       Allegany County      F     child        4541
4          Bronx County      M     child      177091
..                  ...    ...       ...         ...
367  Westchester County      F    senior      100289
368      Wyoming County      M    senior        3905
369      Wyoming County      F    senior        4031
370        Yates County      M    senior        2616
371        Yates County      F    senior        2776

[372 rows x 4 columns]

In [4]:
# above cell is equivalent to

melt_df = pd.melt(
    frame=df,
    id_vars=["county", "gender"],
    value_vars=['child', 'adult', 'senior'],
    var_name="age_group", value_name='population')

melt_df

                 county gender age_group  population
0         Albany County      M     child       29296
1         Albany County      F     child       28137
2       Allegany County      M     child        4803
3       Allegany County      F     child        4541
4          Bronx County      M     child      177091
..                  ...    ...       ...         ...
367  Westchester County      F    senior      100289
368      Wyoming County      M    senior        3905
369      Wyoming County      F    senior        4031
370        Yates County      M    senior        2616
371        Yates County      F    senior        2776

[372 rows x 4 columns]