# Explode
## Explode by one columns
Transform each element of a list-like to a row, replicating index values.

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("../08-core_data_manipulation/data/IMDB Top 250 Movies.csv")

# let's clean the data type
numeric_columns = ["budget",'box_office']

for col in numeric_columns:
    df[col] = df[col].apply(pd.to_numeric, errors='coerce')

df

As you can see, the `genre` column contain multiple values. We wanted to create a new dataframe with one genre per row
### Explode genres

We notice that the `genre` column is not exactly a list, so we cannot explode it directly.

In fact, if you explode it directly, nothing really happens. See the cell below.

In [ ]:
df['genre'].explode().head()

Therefore, we need to transform this `genre` column to lists or other iterable types.
- We can create a new column called `genre_list` using string operations we have learnt
- explode by `genre_list` instead of `genre` itself.

In [ ]:
df['genre_list'] = df['genre'].str.split(",")
df[['name', 'genre_list']].head()

In [ ]:
# Checking the types and confirm the type of genre_list is list
print(type(df['genre'].iloc[0]))
print(type(df['genre_list'].iloc[0]))

In [ ]:
df_exploded = df.explode('genre_list', ignore_index=True)

df_exploded[['rank', 'name','genre','genre_list']]

Now we can inspect genres

In [ ]:
df_exploded['genre_list'].value_counts()

In [ ]:
# there are 21 genres

df_exploded['genre_list'].nunique()

In [ ]:
# Let's plot the distribution of ratings of the top five genres

sns.kdeplot(df_exploded[df_exploded['genre_list'].isin(df_exploded['genre_list'].value_counts().head(5).index)], x='rating', hue='genre_list',
            fill=True)

In [ ]:
sns.boxenplot(df_exploded[df_exploded['genre_list'].isin(df_exploded['genre_list'].value_counts().head(5).index)], y='rating', hue='genre_list',
            gap=0.2)

### Explode actors (casts)

In [9]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("../08-core_data_manipulation/data/IMDB Top 250 Movies.csv")

# let's clean the data type
numeric_columns = ["budget",'box_office']

for col in numeric_columns:
    df[col] = df[col].apply(pd.to_numeric, errors='coerce')

df

,rank,name,year,rating,genre,certificate,run_time,tagline,budget,box_office,casts,directors,writers
0,1,The Shawshank Redemption,1994,9.3,Drama,R,2h 22m,Fear can hold you prisoner. Hope can set you f...,25000000.0,2.888450e+07,"Tim Robbins,Morgan Freeman,Bob Gunton,William ...",Frank Darabont,"Stephen King,Frank Darabont"
1,2,The Godfather,1972,9.2,"Crime,Drama",R,2h 55m,An offer you can't refuse.,6000000.0,2.503418e+08,"Marlon Brando,Al Pacino,James Caan,Diane Keato...",Francis Ford Coppola,"Mario Puzo,Francis Ford Coppola"
2,3,The Dark Knight,2008,9.0,"Action,Crime,Drama",PG-13,2h 32m,Why So Serious?,185000000.0,1.006234e+09,"Christian Bale,Heath Ledger,Aaron Eckhart,Mich...",Christopher Nolan,"Jonathan Nolan,Christopher Nolan,David S. Goyer"
3,4,The Godfather Part II,1974,9.0,"Crime,Drama",R,3h 22m,All the power on earth can't change destiny.,13000000.0,4.796192e+07,"Al Pacino,Robert De Niro,Robert Duvall,Diane K...",Francis Ford Coppola,"Francis Ford Coppola,Mario Puzo"
4,5,12 Angry Men,1957,9.0,"Crime,Drama",Approved,1h 36m,Life Is In Their Hands -- Death Is On Their Mi...,350000.0,9.550000e+02,"Henry Fonda,Lee J. Cobb,Martin Balsam,John Fie...",Sidney Lumet,Reginald Rose
...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,246,The Help,2011,8.1,Drama,PG-13,2h 26m,Change begins with a whisper.,25000000.0,2.166391e+08,"Viola Davis,Emma Stone,Octavia Spencer,Bryce D...",Tate Taylor,"Tate Taylor,Kathryn Stockett"
246,247,Dersu Uzala,1975,8.2,"Adventure,Biography,Drama",G,2h 22m,There is man and beast at nature's mercy. Ther...,4000000.0,1.448000e+04,"Maksim Munzuk,Yuriy Solomin,Mikhail Bychkov,Vl...",Akira Kurosawa,"Akira Kurosawa,Yuriy Nagibin,Vladimir Arsenev"
247,248,Aladdin,1992,8.0,"Animation,Adventure,Comedy",G,1h 30m,Wish granted! (DVD re-release),NaN,NaN,"Scott Weinger,Robin Williams,Linda Larkin,Jona...","Ron Clements,John Musker","Ron Clements,John Musker,Ted Elliott"
248,249,Gandhi,1982,8.0,"Biography,Drama,History",PG,3h 11m,His Triumph Changed The World Forever.,22000000.0,5.276789e+07,"Ben Kingsley,John Gielgud,Rohini Hattangadi,Ro...",Richard Attenborough,John Briley
249,250,Dances with Wolves,1990,8.0,"Adventure,Drama,Western",PG-13,3h 1m,Inside everyone is a frontier waiting to be di...,22000000.0,4.242088e+08,"Kevin Costner,Mary McDonnell,Graham Greene,Rod...",Kevin Costner,Michael Blake

In [10]:
df['cast_list'] = df['casts'].str.split(",")
df['cast_list']

0      [Tim Robbins, Morgan Freeman, Bob Gunton, Will...
1      [Marlon Brando, Al Pacino, James Caan, Diane K...
2      [Christian Bale, Heath Ledger, Aaron Eckhart, ...
3      [Al Pacino, Robert De Niro, Robert Duvall, Dia...
4      [Henry Fonda, Lee J. Cobb, Martin Balsam, John...
                             ...
245    [Viola Davis, Emma Stone, Octavia Spencer, Bry...
246    [Maksim Munzuk, Yuriy Solomin, Mikhail Bychkov...
247    [Scott Weinger, Robin Williams, Linda Larkin, ...
248    [Ben Kingsley, John Gielgud, Rohini Hattangadi...
249    [Kevin Costner, Mary McDonnell, Graham Greene,...
Name: cast_list, Length: 250, dtype: object

In [12]:
df_explode_cast = df.explode('cast_list', ignore_index=True)

df_explode_cast[['name','cast_list']]

                          name            cast_list
0     The Shawshank Redemption          Tim Robbins
1     The Shawshank Redemption       Morgan Freeman
2     The Shawshank Redemption           Bob Gunton
3     The Shawshank Redemption       William Sadler
4     The Shawshank Redemption         Clancy Brown
...                        ...                  ...
4427        Dances with Wolves          Tony Pierce
4428        Dances with Wolves  Doris Leader Charge
4429        Dances with Wolves          Tom Everett
4430        Dances with Wolves         Larry Joshua
4431        Dances with Wolves           Kirk Baltz

[4432 rows x 2 columns]

Now we wanted to see who cast in most top movies.

In [13]:
df_explode_cast['cast_list'].value_counts()

cast_list
Robert De Niro       9
Harrison Ford        7
John Ratzenberger    7
Morgan Freeman       7
Tom Hanks            6
                    ..
Michael Sottile      1
Robert Ruth          1
Lawrence Bender      1
Linda Kaye           1
Larry Joshua         1
Name: count, Length: 3828, dtype: int64

And who generate the most box office?

In [15]:
cast_box_office_total = df_explode_cast.groupby('cast_list', as_index=False)['budget'].sum().sort_values(by='budget',ascending=False)
cast_box_office_total

             cast_list        budget
2028       Keith David  2.421000e+09
358       Billy Crudup  2.420000e+09
76      Alex Fernandez  2.400000e+09
1949    Julia Fletcher  2.400000e+09
1272  Gillian Anderson  2.400000e+09
...                ...           ...
2469      Maude Eburne  0.000000e+00
2471   Maureen McBride  0.000000e+00
2474    Maurice Schutz  0.000000e+00
2476        Max Dietze  0.000000e+00
3827       Özge Özberk  0.000000e+00

[3828 rows x 2 columns]

### Explode by directors

In [16]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("../08-core_data_manipulation/data/IMDB Top 250 Movies.csv")

# let's clean the data type
numeric_columns = ["budget",'box_office']

for col in numeric_columns:
    df[col] = df[col].apply(pd.to_numeric, errors='coerce')

df

,rank,name,year,rating,genre,certificate,run_time,tagline,budget,box_office,casts,directors,writers
0,1,The Shawshank Redemption,1994,9.3,Drama,R,2h 22m,Fear can hold you prisoner. Hope can set you f...,25000000.0,2.888450e+07,"Tim Robbins,Morgan Freeman,Bob Gunton,William ...",Frank Darabont,"Stephen King,Frank Darabont"
1,2,The Godfather,1972,9.2,"Crime,Drama",R,2h 55m,An offer you can't refuse.,6000000.0,2.503418e+08,"Marlon Brando,Al Pacino,James Caan,Diane Keato...",Francis Ford Coppola,"Mario Puzo,Francis Ford Coppola"
2,3,The Dark Knight,2008,9.0,"Action,Crime,Drama",PG-13,2h 32m,Why So Serious?,185000000.0,1.006234e+09,"Christian Bale,Heath Ledger,Aaron Eckhart,Mich...",Christopher Nolan,"Jonathan Nolan,Christopher Nolan,David S. Goyer"
3,4,The Godfather Part II,1974,9.0,"Crime,Drama",R,3h 22m,All the power on earth can't change destiny.,13000000.0,4.796192e+07,"Al Pacino,Robert De Niro,Robert Duvall,Diane K...",Francis Ford Coppola,"Francis Ford Coppola,Mario Puzo"
4,5,12 Angry Men,1957,9.0,"Crime,Drama",Approved,1h 36m,Life Is In Their Hands -- Death Is On Their Mi...,350000.0,9.550000e+02,"Henry Fonda,Lee J. Cobb,Martin Balsam,John Fie...",Sidney Lumet,Reginald Rose
...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,246,The Help,2011,8.1,Drama,PG-13,2h 26m,Change begins with a whisper.,25000000.0,2.166391e+08,"Viola Davis,Emma Stone,Octavia Spencer,Bryce D...",Tate Taylor,"Tate Taylor,Kathryn Stockett"
246,247,Dersu Uzala,1975,8.2,"Adventure,Biography,Drama",G,2h 22m,There is man and beast at nature's mercy. Ther...,4000000.0,1.448000e+04,"Maksim Munzuk,Yuriy Solomin,Mikhail Bychkov,Vl...",Akira Kurosawa,"Akira Kurosawa,Yuriy Nagibin,Vladimir Arsenev"
247,248,Aladdin,1992,8.0,"Animation,Adventure,Comedy",G,1h 30m,Wish granted! (DVD re-release),NaN,NaN,"Scott Weinger,Robin Williams,Linda Larkin,Jona...","Ron Clements,John Musker","Ron Clements,John Musker,Ted Elliott"
248,249,Gandhi,1982,8.0,"Biography,Drama,History",PG,3h 11m,His Triumph Changed The World Forever.,22000000.0,5.276789e+07,"Ben Kingsley,John Gielgud,Rohini Hattangadi,Ro...",Richard Attenborough,John Briley
249,250,Dances with Wolves,1990,8.0,"Adventure,Drama,Western",PG-13,3h 1m,Inside everyone is a frontier waiting to be di...,22000000.0,4.242088e+08,"Kevin Costner,Mary McDonnell,Graham Greene,Rod...",Kevin Costner,Michael Blake

In [17]:
df['director_list']=df['directors'].str.split(",")
df['director_list']

0                 [Frank Darabont]
1           [Francis Ford Coppola]
2              [Christopher Nolan]
3           [Francis Ford Coppola]
4                   [Sidney Lumet]
                  ...
245                  [Tate Taylor]
246               [Akira Kurosawa]
247    [Ron Clements, John Musker]
248         [Richard Attenborough]
249                [Kevin Costner]
Name: director_list, Length: 250, dtype: object

In [19]:
df_exploded_directors = df.explode('director_list', ignore_index=True)

df_exploded_directors

,rank,name,year,rating,genre,certificate,run_time,tagline,budget,box_office,casts,directors,writers,director_list
0,1,The Shawshank Redemption,1994,9.3,Drama,R,2h 22m,Fear can hold you prisoner. Hope can set you f...,25000000.0,2.888450e+07,"Tim Robbins,Morgan Freeman,Bob Gunton,William ...",Frank Darabont,"Stephen King,Frank Darabont",Frank Darabont
1,2,The Godfather,1972,9.2,"Crime,Drama",R,2h 55m,An offer you can't refuse.,6000000.0,2.503418e+08,"Marlon Brando,Al Pacino,James Caan,Diane Keato...",Francis Ford Coppola,"Mario Puzo,Francis Ford Coppola",Francis Ford Coppola
2,3,The Dark Knight,2008,9.0,"Action,Crime,Drama",PG-13,2h 32m,Why So Serious?,185000000.0,1.006234e+09,"Christian Bale,Heath Ledger,Aaron Eckhart,Mich...",Christopher Nolan,"Jonathan Nolan,Christopher Nolan,David S. Goyer",Christopher Nolan
3,4,The Godfather Part II,1974,9.0,"Crime,Drama",R,3h 22m,All the power on earth can't change destiny.,13000000.0,4.796192e+07,"Al Pacino,Robert De Niro,Robert Duvall,Diane K...",Francis Ford Coppola,"Francis Ford Coppola,Mario Puzo",Francis Ford Coppola
4,5,12 Angry Men,1957,9.0,"Crime,Drama",Approved,1h 36m,Life Is In Their Hands -- Death Is On Their Mi...,350000.0,9.550000e+02,"Henry Fonda,Lee J. Cobb,Martin Balsam,John Fie...",Sidney Lumet,Reginald Rose,Sidney Lumet
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
274,247,Dersu Uzala,1975,8.2,"Adventure,Biography,Drama",G,2h 22m,There is man and beast at nature's mercy. Ther...,4000000.0,1.448000e+04,"Maksim Munzuk,Yuriy Solomin,Mikhail Bychkov,Vl...",Akira Kurosawa,"Akira Kurosawa,Yuriy Nagibin,Vladimir Arsenev",Akira Kurosawa
275,248,Aladdin,1992,8.0,"Animation,Adventure,Comedy",G,1h 30m,Wish granted! (DVD re-release),NaN,NaN,"Scott Weinger,Robin Williams,Linda Larkin,Jona...","Ron Clements,John Musker","Ron Clements,John Musker,Ted Elliott",Ron Clements
276,248,Aladdin,1992,8.0,"Animation,Adventure,Comedy",G,1h 30m,Wish granted! (DVD re-release),NaN,NaN,"Scott Weinger,Robin Williams,Linda Larkin,Jona...","Ron Clements,John Musker","Ron Clements,John Musker,Ted Elliott",John Musker
277,249,Gandhi,1982,8.0,"Biography,Drama,History",PG,3h 11m,His Triumph Changed The World Forever.,22000000.0,5.276789e+07,"Ben Kingsley,John Gielgud,Rohini Hattangadi,Ro...",Richard Attenborough,John Briley,Richard Attenborough
278,250,Dances with Wolves,1990,8.0,"Adventure,Drama,Western",PG-13,3h 1m,Inside everyone is a frontier waiting to be di...,22000000.0,4.242088e+08,"Kevin Costner,Mary McDonnell,Graham Greene,Rod...",Kevin Costner,Michael Blake,Kevin Costner

In [20]:
df_exploded_directors['director_list'].value_counts()

director_list
Christopher Nolan    7
Steven Spielberg     7
Akira Kurosawa       7
Martin Scorsese      7
Stanley Kubrick      7
                    ..
Thomas Vinterberg    1
Elem Klimov          1
Michel Gondry        1
Richard Marquand     1
Kevin Costner        1
Name: count, Length: 176, dtype: int64

In [21]:
# whose budget is the highest

df_exploded_directors.groupby("director_list")['budget'].sum().reset_index().sort_values(by='budget',ascending=False)

             director_list        budget
64          Hayao Miyazaki  2.443000e+09
23       Christopher Nolan  9.590000e+08
8            Anthony Russo  6.770000e+08
75               Joe Russo  6.770000e+08
127        Rajkumar Hirani  5.500000e+08
..                     ...           ...
146           Satyajit Ray  0.000000e+00
65   Henri-Georges Clouzot  0.000000e+00
149          Sergio Pablos  0.000000e+00
61            Gus Van Sant  0.000000e+00
0               Aamir Khan  0.000000e+00

[176 rows x 2 columns]

## Explode by multiple columns (sequential)
### Cast and director
Let's say, we wanted to study which cast collaborate with which director the most

In [22]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("../08-core_data_manipulation/data/IMDB Top 250 Movies.csv")

# let's clean the data type
numeric_columns = ["budget",'box_office']

for col in numeric_columns:
    df[col] = df[col].apply(pd.to_numeric, errors='coerce')

df

,rank,name,year,rating,genre,certificate,run_time,tagline,budget,box_office,casts,directors,writers
0,1,The Shawshank Redemption,1994,9.3,Drama,R,2h 22m,Fear can hold you prisoner. Hope can set you f...,25000000.0,2.888450e+07,"Tim Robbins,Morgan Freeman,Bob Gunton,William ...",Frank Darabont,"Stephen King,Frank Darabont"
1,2,The Godfather,1972,9.2,"Crime,Drama",R,2h 55m,An offer you can't refuse.,6000000.0,2.503418e+08,"Marlon Brando,Al Pacino,James Caan,Diane Keato...",Francis Ford Coppola,"Mario Puzo,Francis Ford Coppola"
2,3,The Dark Knight,2008,9.0,"Action,Crime,Drama",PG-13,2h 32m,Why So Serious?,185000000.0,1.006234e+09,"Christian Bale,Heath Ledger,Aaron Eckhart,Mich...",Christopher Nolan,"Jonathan Nolan,Christopher Nolan,David S. Goyer"
3,4,The Godfather Part II,1974,9.0,"Crime,Drama",R,3h 22m,All the power on earth can't change destiny.,13000000.0,4.796192e+07,"Al Pacino,Robert De Niro,Robert Duvall,Diane K...",Francis Ford Coppola,"Francis Ford Coppola,Mario Puzo"
4,5,12 Angry Men,1957,9.0,"Crime,Drama",Approved,1h 36m,Life Is In Their Hands -- Death Is On Their Mi...,350000.0,9.550000e+02,"Henry Fonda,Lee J. Cobb,Martin Balsam,John Fie...",Sidney Lumet,Reginald Rose
...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,246,The Help,2011,8.1,Drama,PG-13,2h 26m,Change begins with a whisper.,25000000.0,2.166391e+08,"Viola Davis,Emma Stone,Octavia Spencer,Bryce D...",Tate Taylor,"Tate Taylor,Kathryn Stockett"
246,247,Dersu Uzala,1975,8.2,"Adventure,Biography,Drama",G,2h 22m,There is man and beast at nature's mercy. Ther...,4000000.0,1.448000e+04,"Maksim Munzuk,Yuriy Solomin,Mikhail Bychkov,Vl...",Akira Kurosawa,"Akira Kurosawa,Yuriy Nagibin,Vladimir Arsenev"
247,248,Aladdin,1992,8.0,"Animation,Adventure,Comedy",G,1h 30m,Wish granted! (DVD re-release),NaN,NaN,"Scott Weinger,Robin Williams,Linda Larkin,Jona...","Ron Clements,John Musker","Ron Clements,John Musker,Ted Elliott"
248,249,Gandhi,1982,8.0,"Biography,Drama,History",PG,3h 11m,His Triumph Changed The World Forever.,22000000.0,5.276789e+07,"Ben Kingsley,John Gielgud,Rohini Hattangadi,Ro...",Richard Attenborough,John Briley
249,250,Dances with Wolves,1990,8.0,"Adventure,Drama,Western",PG-13,3h 1m,Inside everyone is a frontier waiting to be di...,22000000.0,4.242088e+08,"Kevin Costner,Mary McDonnell,Graham Greene,Rod...",Kevin Costner,Michael Blake

In [23]:
df['cast_list'] = df['casts'].str.split(",")
df['director_list']=df['directors'].str.split(",")

df_explode_cast_director = df.explode('cast_list', ignore_index=True).explode('director_list', ignore_index=True)
df_explode_cast_director

,rank,name,year,rating,genre,certificate,run_time,tagline,budget,box_office,casts,directors,writers,cast_list,director_list
0,1,The Shawshank Redemption,1994,9.3,Drama,R,2h 22m,Fear can hold you prisoner. Hope can set you f...,25000000.0,28884504.0,"Tim Robbins,Morgan Freeman,Bob Gunton,William ...",Frank Darabont,"Stephen King,Frank Darabont",Tim Robbins,Frank Darabont
1,1,The Shawshank Redemption,1994,9.3,Drama,R,2h 22m,Fear can hold you prisoner. Hope can set you f...,25000000.0,28884504.0,"Tim Robbins,Morgan Freeman,Bob Gunton,William ...",Frank Darabont,"Stephen King,Frank Darabont",Morgan Freeman,Frank Darabont
2,1,The Shawshank Redemption,1994,9.3,Drama,R,2h 22m,Fear can hold you prisoner. Hope can set you f...,25000000.0,28884504.0,"Tim Robbins,Morgan Freeman,Bob Gunton,William ...",Frank Darabont,"Stephen King,Frank Darabont",Bob Gunton,Frank Darabont
3,1,The Shawshank Redemption,1994,9.3,Drama,R,2h 22m,Fear can hold you prisoner. Hope can set you f...,25000000.0,28884504.0,"Tim Robbins,Morgan Freeman,Bob Gunton,William ...",Frank Darabont,"Stephen King,Frank Darabont",William Sadler,Frank Darabont
4,1,The Shawshank Redemption,1994,9.3,Drama,R,2h 22m,Fear can hold you prisoner. Hope can set you f...,25000000.0,28884504.0,"Tim Robbins,Morgan Freeman,Bob Gunton,William ...",Frank Darabont,"Stephen King,Frank Darabont",Clancy Brown,Frank Darabont
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4944,250,Dances with Wolves,1990,8.0,"Adventure,Drama,Western",PG-13,3h 1m,Inside everyone is a frontier waiting to be di...,22000000.0,424208848.0,"Kevin Costner,Mary McDonnell,Graham Greene,Rod...",Kevin Costner,Michael Blake,Tony Pierce,Kevin Costner
4945,250,Dances with Wolves,1990,8.0,"Adventure,Drama,Western",PG-13,3h 1m,Inside everyone is a frontier waiting to be di...,22000000.0,424208848.0,"Kevin Costner,Mary McDonnell,Graham Greene,Rod...",Kevin Costner,Michael Blake,Doris Leader Charge,Kevin Costner
4946,250,Dances with Wolves,1990,8.0,"Adventure,Drama,Western",PG-13,3h 1m,Inside everyone is a frontier waiting to be di...,22000000.0,424208848.0,"Kevin Costner,Mary McDonnell,Graham Greene,Rod...",Kevin Costner,Michael Blake,Tom Everett,Kevin Costner
4947,250,Dances with Wolves,1990,8.0,"Adventure,Drama,Western",PG-13,3h 1m,Inside everyone is a frontier waiting to be di...,22000000.0,424208848.0,"Kevin Costner,Mary McDonnell,Graham Greene,Rod...",Kevin Costner,Michael Blake,Larry Joshua,Kevin Costner
4948,250,Dances with Wolves,1990,8.0,"Adventure,Drama,Western",PG-13,3h 1m,Inside everyone is a frontier waiting to be di...,22000000.0,424208848.0,"Kevin Costner,Mary McDonnell,Graham Greene,Rod...",Kevin Costner,Michael Blake,Kirk Baltz,Kevin Costner

In [24]:
df_explode_cast_director[['cast_list','director_list']].value_counts()

cast_list           director_list
Michael Caine       Christopher Nolan    6
Takashi Shimura     Akira Kurosawa       5
Charles Chaplin     Charles Chaplin      5
Minoru Chiaki       Akira Kurosawa       4
Henry Bergman       Charles Chaplin      4
                                        ..
Giovanni Ribisi     Steven Spielberg     1
Giovanni Corporale  Vittorio De Sica     1
Giorgio Cantarini   Roberto Benigni      1
Gio Petré           Ingmar Bergman       1
Özge Özberk         Çagan Irmak          1
Name: count, Length: 4724, dtype: int64

In [ ]:
cast_name, director_name = 'Takashi Shimura', 'Akira Kurosawa'
df_explode_cast_director[(df_explode_cast_director['cast_list']==cast_name) & (df_explode_cast_director['director_list']==director_name)]

In [ ]:
# Another way to do it is to create a list of movies in the grouped dataframe

df_explode_cast_director.groupby(['cast_list','director_list'], as_index=False).agg(
    count=('cast_list', 'count'),
    movies=('name', list),
    box_office_million=('box_office', lambda x: (x.sum()/1_000_000))
).sort_values(by='count',ascending=False)

### Director and writer

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("../08-core_data_manipulation/data/IMDB Top 250 Movies.csv")

# let's clean the data type
numeric_columns = ["budget",'box_office']

for col in numeric_columns:
    df[col] = df[col].apply(pd.to_numeric, errors='coerce')

df

In [ ]:
director_write_pair = (df.assign(
    director_list = df['directors'].str.split(","),
    writer_list = df['writers'].str.split(",")
).
explode('director_list', ignore_index=True).explode('writer_list', ignore_index=True).
                       groupby(['director_list','writer_list'], as_index=False).agg(
    count=('director_list', 'count'),
    movies=('name', list),
    box_office_million=('box_office', lambda x: (x.sum()/1_000_000)),
    mean_rating=('rating', 'mean')
)).assign(
    mean_box_office = lambda x: x['box_office_million']/x['count']
).sort_values(by='mean_rating',ascending=False)

director_write_pair