# Advanced String Operations
## Split strings
### Basic splitting

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("../06-Exploratory_data_analysis/data/Titanic-Dataset.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [11]:
# Note: here I split the name using ", " instead of ","

df["Name"].str.split(", ").head()

0                            [Braund, Mr. Owen Harris]
1    [Cumings, Mrs. John Bradley (Florence Briggs T...
2                             [Heikkinen, Miss. Laina]
3       [Futrelle, Mrs. Jacques Heath (Lily May Peel)]
4                           [Allen, Mr. William Henry]
Name: Name, dtype: object

### Split and expand
Create multiple new columns using `.str.split(expand=True)`

In [15]:
df[["last_name", "rest"]] = df["Name"].str.split(", ", expand=True)

df[["Name","last_name","rest"]].head()

,Name,last_name,rest
0,"Braund, Mr. Owen Harris",Braund,Mr. Owen Harris
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Cumings,Mrs. John Bradley (Florence Briggs Thayer)
2,"Heikkinen, Miss. Laina",Heikkinen,Miss. Laina
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Futrelle,Mrs. Jacques Heath (Lily May Peel)
4,"Allen, Mr. William Henry",Allen,Mr. William Henry

### Split using regular expression

For example, if we observe the name column, we see a pattern, for example, "Futrelle, Mrs. Jacques Heath (Lily May Peel)", this includes multiple name components.

If we wanted to split the name column into `last_name`, `title`, `first_middle_name`, and `alternative_name`:

In [36]:
import re
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("../06-Exploratory_data_analysis/data/Titanic-Dataset.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [45]:

df[['last_name', 'title', 'first_middle_name', 'alternative_name']] = df['Name'].str.split(r'\s*[,.()]\s*', expand=True, n=3)

df[['Name','last_name', 'title', 'first_middle_name', 'alternative_name']].head()

,Name,last_name,title,first_middle_name,alternative_name
0,"Braund, Mr. Owen Harris",Braund,Mr,Owen Harris,None
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Cumings,Mrs,John Bradley,Florence Briggs Thayer)
2,"Heikkinen, Miss. Laina",Heikkinen,Miss,Laina,None
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Futrelle,Mrs,Jacques Heath,Lily May Peel)
4,"Allen, Mr. William Henry",Allen,Mr,William Henry,None

In [46]:
df['alternative_name'] = df['alternative_name'].str.strip(to_strip=")")

df[['Name','last_name', 'title', 'first_middle_name', 'alternative_name']].head()

,Name,last_name,title,first_middle_name,alternative_name
0,"Braund, Mr. Owen Harris",Braund,Mr,Owen Harris,None
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Cumings,Mrs,John Bradley,Florence Briggs Thayer
2,"Heikkinen, Miss. Laina",Heikkinen,Miss,Laina,None
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Futrelle,Mrs,Jacques Heath,Lily May Peel
4,"Allen, Mr. William Henry",Allen,Mr,William Henry,None

## Extract patterns: `.str.extract()`
### Example 1: extract titles from Titanic dataset

Explanation of the regex:
- `,`:	Match the comma that appears before the title
- `\s*`:	Match zero or more spaces after the comma
- `( )`:	Capture group (this is what pandas extracts)
- `[^\.]+`:	Match one or more characters that are NOT a period
- `\.`:	Match the period after the title

In [47]:
import re
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("../06-Exploratory_data_analysis/data/Titanic-Dataset.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [48]:

title_extract_pattern = re.compile(r',\s*([^\.]+)\.')

df["title"] = df["Name"].str.extract(title_extract_pattern)

df[["Name", "title"]].head()

                                                Name title
0                            Braund, Mr. Owen Harris    Mr
1  Cumings, Mrs. John Bradley (Florence Briggs Th...   Mrs
2                             Heikkinen, Miss. Laina  Miss
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)   Mrs
4                           Allen, Mr. William Henry    Mr

### Example 2: extract email domains

Explanation of the regex:
- `@`:  Literal, matches the "@" character literally in the string.
- `( )`:    Capturing Group, These parentheses group the characters together, allowing you to extract the specific part of the text that matches what is inside, without including the "@" symbol itself in the capture.
- `.`:  Any character (except newline character)
- `+`:  One or more occurrences

In [52]:
emails = pd.Series([
    "tony.stark@gmail.com",
    "Elon.musk@tesla.com",
    "neo.anderson@matrix.ai",
    "jieshu.wang@stonybrook.edu"
])

email_extract_pattern = re.compile(r'@(.+)$')

domains = emails.str.extract(email_extract_pattern)

domains

                0
0       gmail.com
1       tesla.com
2       matrix.ai
3  stonybrook.edu

## Concatenate Strings

### Example 1: concat names
`.str.cat()`

In [56]:
import pandas as pd
import numpy as np

df_users = pd.DataFrame({
    "title": ["Ms.", "Mr.", "Mr."],
    "first": ["Alice", "Bob", "Charlie"],
    "last": ["Smith", "Lee", "Brown"]
})

df_users.head()

  title    first   last
0   Ms.    Alice  Smith
1   Mr.      Bob    Lee
2   Mr.  Charlie  Brown

In [58]:
df_users["full_name"] = df_users["title"].str.cat(df_users[["first",'last']], sep=" ")

df_users

  title    first   last          full_name
0   Ms.    Alice  Smith    Ms. Alice Smith
1   Mr.      Bob    Lee        Mr. Bob Lee
2   Mr.  Charlie  Brown  Mr. Charlie Brown

### Example 2: create email address for students

Imagine we have a group of new students coming to Stony Brook University, and we need to assign them new email address. The address would be their first name, a dot, last name, a dot, and a random three-digit number (zfill with 0), and @stonybrook.edu

In [72]:
import pandas as pd

df = pd.DataFrame({
    "first_name": [
        "Harry", "Jieshu", "Frodo", "Leia", "Tony",
        "Bruce", "Peter", "Katniss", "Neo"
    ],
    "last_name": [
        "Potter", "Wang", "Baggins", "Organa", "Stark",
        "Wayne", "Parker", "Everdeen", "Anderson"
    ]
})

df

  first_name last_name
0      Harry    Potter
1     Jieshu      Wang
2      Frodo   Baggins
3       Leia    Organa
4       Tony     Stark
5      Bruce     Wayne
6      Peter    Parker
7    Katniss  Everdeen
8        Neo  Anderson

In [73]:
#A dd random 3-digit (or fewer) numbers

df["id"] = np.random.randint(0, 1000, size=len(df))

# Convert numbers to string
df["id"] = df["id"].astype(str)

df['id'] = df['id'].str.zfill(3)

df

  first_name last_name   id
0      Harry    Potter  185
1     Jieshu      Wang  830
2      Frodo   Baggins  869
3       Leia    Organa  134
4       Tony     Stark  093
5      Bruce     Wayne  930
6      Peter    Parker  091
7    Katniss  Everdeen  488
8        Neo  Anderson  796

In [75]:
# Use .str.cat() to build email

df["email"] = (
    df["first_name"].str.lower()
    .str.cat(df["last_name"].str.lower(), sep=".")
    .str.cat(df["id"], sep=".")
    .str.cat(pd.Series(["@stonybrook.edu"] * len(df)))
)

df

  first_name last_name   id                                email
0      Harry    Potter  185      harry.potter.185@stonybrook.edu
1     Jieshu      Wang  830       jieshu.wang.830@stonybrook.edu
2      Frodo   Baggins  869     frodo.baggins.869@stonybrook.edu
3       Leia    Organa  134       leia.organa.134@stonybrook.edu
4       Tony     Stark  093        tony.stark.093@stonybrook.edu
5      Bruce     Wayne  930       bruce.wayne.930@stonybrook.edu
6      Peter    Parker  091      peter.parker.091@stonybrook.edu
7    Katniss  Everdeen  488  katniss.everdeen.488@stonybrook.edu
8        Neo  Anderson  796      neo.anderson.796@stonybrook.edu

## Counting Occurrences: `.str.count()`

Example: Count number of hashtags in posts.

In [80]:
import pandas as pd
import numpy as np
import re

posts = pd.Series([
    "Loving #AI and #DataScience",
    "#Python is great",
    "No hashtags here"
], name='post')
posts

0    Loving #AI and #DataScience
1               #Python is great
2               No hashtags here
Name: post, dtype: object

In [86]:
pd.DataFrame({'post':posts,
             "hashtag_count":posts.str.count("#")})

                          post  hashtag_count
0  Loving #AI and #DataScience              2
1             #Python is great              1
2             No hashtags here              0

## Regex Matching:

We have talked about using `.str.contains()`, which is a powerful tool if combined with regular expressions.

We can also use `.str.match()`, `.str.findall()`, `.str.extract()`, and `.str.replace()` with regex matching.

Example:
- check whether phone number is valid
- extract area code

In [108]:
import pandas as pd
import numpy as np
import re

df = pd.DataFrame({
    "name": ["Tony", "Bruce", "Peter", "Diana", "Clark", "Natasha"],
    "phone": [
        "(631)555-1234",   # valid
        "212 555 5678",   # valid
        "(516)-555-9999",     # valid
        "719-45-6789",    # invalid
        "800-555-000",    # invalid
        "917-555-4321"    # valid
    ]
})

df

      name           phone
0     Tony   (631)555-1234
1    Bruce    212 555 5678
2    Peter  (516)-555-9999
3    Diana     719-45-6789
4    Clark     800-555-000
5  Natasha    917-555-4321

In [109]:
# Validate whether the phone number is valid
phone_pattern = re.compile(r"^\(?(\d{3})\)?([ -]?)\d{3}([ -]?)\d{4}$")

df['valid_phone_number'] = df['phone'].str.match(phone_pattern)

df

      name           phone  valid_phone_number
0     Tony   (631)555-1234                True
1    Bruce    212 555 5678                True
2    Peter  (516)-555-9999                True
3    Diana     719-45-6789               False
4    Clark     800-555-000               False
5  Natasha    917-555-4321                True

In [110]:
# extract area code

df["area_code"] = df["phone"].str.extract(phone_pattern)[0]

df

      name           phone  valid_phone_number area_code
0     Tony   (631)555-1234                True       631
1    Bruce    212 555 5678                True       212
2    Peter  (516)-555-9999                True       516
3    Diana     719-45-6789               False       NaN
4    Clark     800-555-000               False       NaN
5  Natasha    917-555-4321                True       917

## Accessing String Components

In [111]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("../06-Exploratory_data_analysis/data/Titanic-Dataset.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### Indexing

In [112]:
df['Name'].str[0:5]

0      Braun
1      Cumin
2      Heikk
3      Futre
4      Allen
       ...
886    Montv
887    Graha
888    Johns
889    Behr,
890    Doole
Name: Name, Length: 891, dtype: object

### Length

In [115]:
df['Name'].str.len()

0      23
1      51
2      22
3      44
4      24
       ..
886    21
887    28
888    40
889    21
890    19
Name: Name, Length: 891, dtype: int64

### Access element after split
example: access last name

In [116]:
df['Name'].str.split(', ').str[0]

0         Braund
1        Cumings
2      Heikkinen
3       Futrelle
4          Allen
         ...
886     Montvila
887       Graham
888     Johnston
889         Behr
890       Dooley
Name: Name, Length: 891, dtype: object

## A real-world example: extract citation information

We wanted to extract first author last name, year of the publication, publication names, and journal names (if applicable) from raw APA citation strings.

In [138]:
import pandas as pd
import numpy as np
import re

citation_df = pd.DataFrame({
    "apa_reference": [
        'Wang, J., & Lobo, J. (2024). Extensive growth of inventions: Evidence from US patenting. Technological Forecasting and Social Change, 207, 123586. https://doi.org/10.1016/j.techfore.2024.123586',
        'LeCun, Y., Bengio, Y., & Hinton, G. (2015). Deep learning. Nature, 521(7553), 436. https://doi.org/10.1038/nature14539',
        'Wang, J., & Maynard, A. (2025). Gender disparity in US patenting. Humanities and Social Sciences Communications, 12(1), 1730. https://doi.org/10.1057/s41599-025-06038-6',
        'Vaswani, A., Shazeer, N., Parmar, N., Uszkoreit, J., Jones, L., Gomez, A. N., Kaiser, L., & Polosukhin, I. (2023). Attention Is All You Need. arXiv. https://doi.org/10.48550/arXiv.1706.03762',
        'Krizhevsky, A., Sutskever, I., & Hinton, G. (2017). ImageNet classification with deep convolutional neural networks. Communications of the ACM, 60(6), 84–90. https://doi.org/10.1145/3065386',
        'Wang, J., Gundogdu, T. B., Ivic, R. K., Butler, B. S., & Lee, M. (2025). News Deserts as Information Problems: A Case Study of Local News Coverage in Alabama. Proceedings of the Association for Information Science and Technology, 62(1), 741–753. https://doi.org/10.1002/pra2.1293'
                      ]
})

citation_df

                                       apa_reference
0  Wang, J., & Lobo, J. (2024). Extensive growth ...
1  LeCun, Y., Bengio, Y., & Hinton, G. (2015). De...
2  Wang, J., & Maynard, A. (2025). Gender dispari...
3  Vaswani, A., Shazeer, N., Parmar, N., Uszkorei...
4  Krizhevsky, A., Sutskever, I., & Hinton, G. (2...
5  Wang, J., Gundogdu, T. B., Ivic, R. K., Butler...

In [139]:
# write regex patterns

apa_pattern = re.compile(r'^([^,]+),.*?\((\d{4})\)\.\s*(.*?)\.\s*([^,\.]+).*?\s+(https?://\S+)?$')

citation_df[[
    "first_author_last_name",
    "year",
    "publication_title",
    "journal_or_publisher","url"
]] = citation_df["apa_reference"].str.extract(apa_pattern)

citation_df

,apa_reference,first_author_last_name,year,publication_title,journal_or_publisher,url
0,"Wang, J., & Lobo, J. (2024). Extensive growth ...",Wang,2024,Extensive growth of inventions: Evidence from ...,Technological Forecasting and Social Change,https://doi.org/10.1016/j.techfore.2024.123586
1,"LeCun, Y., Bengio, Y., & Hinton, G. (2015). De...",LeCun,2015,Deep learning,Nature,https://doi.org/10.1038/nature14539
2,"Wang, J., & Maynard, A. (2025). Gender dispari...",Wang,2025,Gender disparity in US patenting,Humanities and Social Sciences Communications,https://doi.org/10.1057/s41599-025-06038-6
3,"Vaswani, A., Shazeer, N., Parmar, N., Uszkorei...",Vaswani,2023,Attention Is All You Need,arXiv,https://doi.org/10.48550/arXiv.1706.03762
4,"Krizhevsky, A., Sutskever, I., & Hinton, G. (2...",Krizhevsky,2017,ImageNet classification with deep convolutiona...,Communications of the ACM,https://doi.org/10.1145/3065386
5,"Wang, J., Gundogdu, T. B., Ivic, R. K., Butler...",Wang,2025,News Deserts as Information Problems: A Case S...,Proceedings of the Association for Information...,https://doi.org/10.1002/pra2.1293