# Advanced filtering


## Refresh basic boolean filtering

Use the Titanic dataset again

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("../06-Exploratory_data_analysis/data/Titanic-Dataset.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

Select adult passengers (Age > 18).

Note:
- if you intend to modify the filtered dataframe, make sure you make a copy, e.g., `adults = df[df['age'] > 10].copy()`.

In [2]:
adults = df[df["Age"] >= 18]

adults[["Name","Age","Sex"]].head()

                                                Name   Age     Sex
0                            Braund, Mr. Owen Harris  22.0    male
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  female
2                             Heikkinen, Miss. Laina  26.0  female
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  female
4                           Allen, Mr. William Henry  35.0    male

In [ ]:
df['Age'] >= 18

### Alternatives: using Pandas built-in comparison methods

The same filters can be achieved by using pandas methods:

- `.gt()`: greater than
- `.lt()`: less than
- `.ge()`: greater than or equal to
- `.le()`: less than or equal to

Note: the advantage of those methods is for more complex pipeline or method chaining.

In [3]:
adults = df[df["Age"].ge(18)]

adults[["Name","Age","Sex"]].head()

                                                Name   Age     Sex
0                            Braund, Mr. Owen Harris  22.0    male
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  female
2                             Heikkinen, Miss. Laina  26.0  female
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  female
4                           Allen, Mr. William Henry  35.0    male

or, if we wanted to filter children.

In [6]:
children = df[df['Age'].lt(18)]

children[["Name","Age","Sex"]].head()

                                    Name   Age     Sex
7         Palsson, Master. Gosta Leonard   2.0    male
9    Nasser, Mrs. Nicholas (Adele Achem)  14.0  female
10       Sandstrom, Miss. Marguerite Rut   4.0  female
14  Vestrom, Miss. Hulda Amanda Adolfina  14.0  female
16                  Rice, Master. Eugene   2.0    male

### Filtering with Multiple Conditions
#### "AND" conditions: `&`
Example: female passengers in first class

Important rule: Each condition must be inside parentheses.

In [7]:
first_class_women = df[
    (df["Sex"] == "female") & (df["Pclass"] == 1)
]

first_class_women[["Name","Sex","Pclass"]].head()

                                                 Name     Sex  Pclass
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female       1
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female       1
11                           Bonnell, Miss. Elizabeth  female       1
31     Spencer, Mrs. William Augustus (Marie Eugenie)  female       1
52           Harper, Mrs. Henry Sleeper (Myna Haxtun)  female       1

#### "OR" conditions: `|`

Example: passengers who are children OR elderly

In [9]:
young_or_old = df[
    (df["Age"] < 18) | (df["Age"] > 60)
]

young_or_old[["Name","Age"]]

                                     Name   Age
7          Palsson, Master. Gosta Leonard   2.0
9     Nasser, Mrs. Nicholas (Adele Achem)  14.0
10        Sandstrom, Miss. Marguerite Rut   4.0
14   Vestrom, Miss. Hulda Amanda Adolfina  14.0
16                   Rice, Master. Eugene   2.0
..                                    ...   ...
851                   Svensson, Mr. Johan  74.0
852               Boulos, Miss. Nourelain   9.0
853             Lines, Miss. Mary Conover  16.0
869       Johnson, Master. Harold Theodor   4.0
875      Najib, Miss. Adele Kiamie "Jane"  15.0

[135 rows x 2 columns]

### Negation of conditions

Example: Select passengers who are NOT children.

Important Note: the difference between `df[df["Age"] >= 18)]` and `df[~(df["Age"] < 18)]` is that the former only select passengers whose age is equal to or greater than 18, but the latter will also select NaN values.

In [13]:
not_children = df[~(df["Age"] <18)]

not_children[["Name","Age"]]

                                                  Name   Age
0                              Braund, Mr. Owen Harris  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                             Allen, Mr. William Henry  35.0
..                                                 ...   ...
886                              Montvila, Rev. Juozas  27.0
887                       Graham, Miss. Margaret Edith  19.0
888           Johnston, Miss. Catherine Helen "Carrie"   NaN
889                              Behr, Mr. Karl Howell  26.0
890                                Dooley, Mr. Patrick  32.0

[778 rows x 2 columns]

### Practical Examples
#### Example #1

Find third-class adult male passengers with very low fare.

In [ ]:
low_fare_passengers = df[
    (df["Pclass"] == 3) &
    (df["Sex"] == "male") &
    (df["Fare"] < 10) &
    (~(df["Age"] < 18)) # You can use df['Age'] >= 18 but here is just a nice exercise
]

low_fare_passengers[["Name","Pclass","Sex", "Age", "Fare"]].head()

#### Example #2
Check survival rate of children vs adults.

In [ ]:
children = df[df["Age"] < 18]
adults = df[df["Age"] >= 18]

print(f"Children survival rate: {children['Survived'].mean():.2f}")
print(f"Adult survival rate: {adults['Survived'].mean():.2f}")

## Advanced Filtering
### Check whether values belong to a set of categories

Use `.isin()`

Example: Select passengers from Southampton or Cherbourg.

In the Titanic dataset, the `Embarked` column indicates the port where a passenger boarded, categorized as C (Cherbourg), Q (Queenstown), or S (Southampton).

In [14]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("../06-Exploratory_data_analysis/data/Titanic-Dataset.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df[(df['Embarked'] == 'S') | (df['Embarked'] == 'C')]

In [15]:
df[df["Embarked"].isin(["S", "C"])][["Name", "Embarked"]]

                                                  Name Embarked
0                              Braund, Mr. Owen Harris        S
1    Cumings, Mrs. John Bradley (Florence Briggs Th...        C
2                               Heikkinen, Miss. Laina        S
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)        S
4                             Allen, Mr. William Henry        S
..                                                 ...      ...
884                             Sutehall, Mr. Henry Jr        S
886                              Montvila, Rev. Juozas        S
887                       Graham, Miss. Margaret Edith        S
888           Johnston, Miss. Catherine Helen "Carrie"        S
889                              Behr, Mr. Karl Howell        C

[812 rows x 2 columns]

Or, if we wanted to select passengers who (1) boarded at Southampton or Cherbourg, and (2) in the first or second class.

In [16]:
df[
    (df['Embarked'].isin(['S', 'C'])) &
    (df['Pclass'].isin([1, 2]))
][["Name", "Embarked",'Pclass']]

                                                  Name Embarked  Pclass
1    Cumings, Mrs. John Bradley (Florence Briggs Th...        C       1
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)        S       1
6                              McCarthy, Mr. Timothy J        S       1
9                  Nasser, Mrs. Nicholas (Adele Achem)        C       2
11                            Bonnell, Miss. Elizabeth        S       1
..                                                 ...      ...     ...
880       Shelley, Mrs. William (Imanita Parrish Hall)        S       2
883                      Banfield, Mr. Frederick James        S       2
886                              Montvila, Rev. Juozas        S       2
887                       Graham, Miss. Margaret Edith        S       1
889                              Behr, Mr. Karl Howell        C       1

[393 rows x 3 columns]

### Filtering by Range: `.between()`

Example: passengers aged between 1 and 4, inclusive.

In [19]:
df[df["Age"].between(left=1, right=3, inclusive="both")][["Name","Age"]]

                                         Name  Age
7              Palsson, Master. Gosta Leonard  2.0
16                       Rice, Master. Eugene  2.0
43   Laroche, Miss. Simonne Marie Anne Andree  3.0
119         Andersson, Miss. Ellis Anna Maria  2.0
164              Panula, Master. Eino Viljami  1.0
172              Johnson, Miss. Eleanor Ileen  1.0
183                 Becker, Master. Richard F  1.0
193                Navratil, Master. Michel M  3.0
205                Strom, Miss. Telma Matilda  2.0
261         Asplund, Master. Edvin Rojj Felix  3.0
297              Allison, Miss. Helen Loraine  2.0
340            Navratil, Master. Edmond Roger  2.0
348    Coutts, Master. William Loch "William"  3.0
374                Palsson, Miss. Stina Viola  3.0
381               Nakid, Miss. Maria ("Mary")  1.0
386           Goodwin, Master. Sidney Leonard  1.0
407            Richards, Master. William Rowe  3.0
479                  Hirvonen, Miss. Hildur E  2.0
530                  Quick, Miss. Phyllis May  2.0
642             Skoog, Miss. Margit Elizabeth  2.0
788                Dean, Master. Bertram Vere  1.0
824              Panula, Master. Urho Abraham  2.0
827                     Mallet, Master. Andre  1.0

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q
43,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.0,1,2,SC/Paris 2123,41.5792,NaN,C
119,120,0,3,"Andersson, Miss. Ellis Anna Maria",female,2.0,4,2,347082,31.2750,NaN,S
164,165,0,3,"Panula, Master. Eino Viljami",male,1.0,4,1,3101295,39.6875,NaN,S
172,173,1,3,"Johnson, Miss. Eleanor Ileen",female,1.0,1,1,347742,11.1333,NaN,S
183,184,1,2,"Becker, Master. Richard F",male,1.0,2,1,230136,39.0000,F4,S
193,194,1,2,"Navratil, Master. Michel M",male,3.0,1,1,230080,26.0000,F2,S
205,206,0,3,"Strom, Miss. Telma Matilda",female,2.0,0,1,347054,10.4625,G6,S
261,262,1,3,"Asplund, Master. Edvin Rojj Felix",male,3.0,4,2,347077,31.3875,NaN,S
297,298,0,1,"Allison, Miss. Helen Loraine",female,2.0,1,2,113781,151.5500,C22 C26,S
340,341,1,2,"Navratil, Master. Edmond Roger",male,2.0,1,1,230080,26.0000,F2,S
348,349,1,3,"Coutts, Master. William Loch ""William""",male,3.0,1,1,C.A. 37671,15.9000,NaN,S
374,375,0,3,"Palsson, Miss. Stina Viola",female,3.0,3,1,349909,21.0750,NaN,S
381,382,1,3,"Nakid, Miss. Maria (""Mary"")",female,1.0,0,2,2653,15.7417,NaN,C
386,387,0,3,"Goodwin, Master. Sidney Leonard",male,1.0,5,2,CA 2144,46.9000,NaN,S
407,408,1,2,"Richards, Master. William Rowe",male,3.0,1,1,29106,18.7500,NaN,S
479,480,1,3,"Hirvonen, Miss. Hildur E",female,2.0,0,1,3101298,12.2875,NaN,S
530,531,1,2,"Quick, Miss. Phyllis May",female,2.0,1,1,26360,26.0000,NaN,S
642,643,0,3,"Skoog, Miss. Margit Elizabeth",female,2.0,3,2,347088,27.9000,NaN,S
788,789,1,3,"Dean, Master. Bertram Vere",male,1.0,1,2,C.A. 2315,20.5750,NaN,S
824,825,0,3,"Panula, Master. Urho Abraham",male,2.0,4,1,3101295,39.6875,NaN,S
827,828,1,2,"Mallet, Master. Andre",male,1.0,0,2,S.C./PARIS 2079,37.0042,NaN,C

The code above is equivalent to `(df["Age"] >= 1) & (df["Age"] <= 4)` but easy to read.

Note: `.between()` can also pass strings as left or right values. In this case, the strings are compared lexicographically (in alphabetical order). example:

In [ ]:
df[df['Name'].between(left="Alice", right="Bob")][['Name']]

### Filtering Using String Methods

These operate on text columns.

#### `.str.contains()`

Example: passengers whose name contains "Smith".

Note that the difference between setting `case=True` and `case=False`.

In [21]:
df[df["Name"].str.contains("Smith", na=False, case=True)][["Name"]]

                           Name
174     Smith, Mr. James Clinch
260           Smith, Mr. Thomas
284  Smith, Mr. Richard William
346   Smith, Miss. Marion Elsie

#### `.str.startswith()`
Example: Passengers whose name starts with "Smith".

In [22]:
df[df["Name"].str.startswith("Smith", na=False)][["Name"]]

                           Name
174     Smith, Mr. James Clinch
260           Smith, Mr. Thomas
284  Smith, Mr. Richard William
346   Smith, Miss. Marion Elsie

#### `.str.endswith()`

Example: passengers whose cabin ends with "5".

In [24]:
df[df["Cabin"].str.endswith("4", na=False)][["Name","Cabin"]]

                                                  Name    Cabin
183                          Becker, Master. Richard F       F4
194          Brown, Mrs. James Joseph (Margaret Tobin)       B4
263                              Harrison, Mr. William      B94
310                     Hays, Miss. Margaret Bechstein      C54
319  Spedden, Mrs. Frederic Oakley (Margaretta Corn...      E34
331                                Partner, Mr. Austen     C124
434                          Silvey, Mr. William Baird      E44
445                          Dodge, Master. Washington      A34
449                     Peuchen, Major. Arthur Godfrey     C104
475                        Clifford, Mr. George Quincy      A14
577          Silvey, Mrs. William Baird (Alice Munger)      E44
618                        Becker, Miss. Marion Louise       F4
700  Astor, Mrs. John Jacob (Madeleine Talmadge Force)  C62 C64
701                   Silverthorne, Mr. Spencer Victor      E24
707                  Calderhead, Mr. Edward Pennington      E24
711                                 Klaber, Mr. Herman     C124
789                           Guggenheim, Mr. Benjamin  B82 B84
867               Roebling, Mr. Washington Augustus II      A24

#### `.str.isnumeric()`
Check whether a string column contains only numbers.

Example: numeric ticket numbers.

In [27]:
df[df["Ticket"].str.isnumeric()][["Ticket","Name"]].head()

   Ticket                                          Name
3  113803  Futrelle, Mrs. Jacques Heath (Lily May Peel)
4  373450                      Allen, Mr. William Henry
5  330877                              Moran, Mr. James
6   17463                       McCarthy, Mr. Timothy J
7  349909                Palsson, Master. Gosta Leonard

### `.nlargest()` and `.nsmallest()`

Quickly find top or bottom values without sorting the entire dataframe.

In [ ]:
# Top 5 most expensive tickets.

df.nlargest(5, "Fare")[["Name","Fare","Pclass"]]

In [ ]:
# Smallest fares

df.nsmallest(5, "Fare")[["Name","Fare","Pclass"]]

### `.any()` and `.all()`

- `axis=1`: evaluate across columns for each row
- `axis=0`: evaluate across rows for each columns

#### `.any()`
Example: find passengers where any family member is present (either SibSp or Parch > 0).

In [ ]:
# first, we can create a condition called family_condition, which is a Dataframe with two Series with True or False values

family_condition = df[["SibSp", "Parch"]] > 0

family_condition

In [ ]:
# Now check if any column is True for each row.

passengers_with_any_family = df[family_condition.any(axis=1)][["Name","SibSp","Parch"]]

passengers_with_any_family

In [ ]:
# The above code is equivalent to the following code:

passengers_with_any_family = df[(df[["SibSp", "Parch"]]>0).any(axis=1)][["Name","SibSp","Parch"]]

passengers_with_any_family

In [ ]:
# Also equivalent to the following code (without using .any():

passengers_with_any_family = df[((df['SibSp'] > 0) | (df['Parch'] > 0))][["Name","SibSp","Parch"]]

passengers_with_any_family

#### `.all()`
Example: find passengers who have both siblings/spouses AND parents/children onboard.

In [ ]:
family_condition = df[["SibSp", "Parch"]] > 0

df[family_condition.all(axis=1)][["Name","SibSp","Parch"]]

In [ ]:
# this is equivalent to

df[(df['SibSp'] > 0) & (df['Parch'] > 0)][["Name","SibSp","Parch"]]

## Common mistakes
### Using `and` and `or` instead of `&` and `|`

Wrong:

In [ ]:

try:
    df[(df['Age']>18) and (df['Sex'] == "female")].head()
except Exception as e:
    print(e)

Correct:

In [ ]:
df[(df['Age']>18) & (df['Sex'] == "female")].head()

### Missing Parentheses
wrong:

In [ ]:
try:
    df[df["Age"] > 30 & df["Fare"] > 50].head()
except Exception as e:
    print(e)

Correct:

In [ ]:
df[(df["Age"] > 30) & (df["Fare"] > 50)].head()

### Accidentally Modifying Filtered Data

Wrong:

In [ ]:
# Note that this does not 100% modify the original dataframe but it might. The problem is it is uncertain.

subset = df[df["Age"] > 30]
subset["family_size"] = subset['Parch'] + subset['SibSp'] + 1

In [ ]:
# If you don't want to by accident modify the original dataframe, just use .copy()

subset = df[df["Age"] > 30].copy()
subset["family_size"] = subset['Parch'] + subset['SibSp'] + 1

### Using `=` instead of `==` for checking equal
wrong:

In [ ]:
df[df['Age'] = 18]

correct:

In [ ]:
df[df['Age'] == 18]

### Forgetting `.str` for string methods
wrong:

In [ ]:
try:
    df[df["Name"].contains("Smith")]
except Exception as e:
    print(e)

In [ ]:
df[df["Name"].str.contains("Smith")]