# Advanced filtering


## Refresh basic boolean filtering

Use the Titanic dataset again

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("../06-Exploratory_data_analysis/data/Titanic-Dataset.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

Select adult passengers (Age > 18).

Note:
- if you intend to modify the filtered dataframe, make sure you make a copy, e.g., `adults = df[df['age'] > 10].copy()`.

In [15]:
adults = df[df["Age"] >= 18]

adults[["Name","Age","Sex"]].head()

                                                Name   Age     Sex
0                            Braund, Mr. Owen Harris  22.0    male
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  female
2                             Heikkinen, Miss. Laina  26.0  female
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  female
4                           Allen, Mr. William Henry  35.0    male

In [16]:
df['Age'] >= 18

0       True
1       True
2       True
3       True
4       True
       ...
886     True
887     True
888    False
889     True
890     True
Name: Age, Length: 891, dtype: bool

### Alternatives: using Pandas built-in comparison methods

The same filters can be achieved by using pandas methods:

- `.gt()`: greater than
- `.lt()`: less than
- `.ge()`: greater than or equal to
- `.le()`: less than or equal to

Note: the advantage of those methods is for more complex pipeline or method chaining.

In [17]:
adults = df[df["Age"].ge(18)]

adults[["Name","Age","Sex"]].head()

                                                Name   Age     Sex
0                            Braund, Mr. Owen Harris  22.0    male
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  female
2                             Heikkinen, Miss. Laina  26.0  female
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  female
4                           Allen, Mr. William Henry  35.0    male

or, if we wanted to filter children.

In [18]:
children = df[df['Age'].lt(18)]

children[["Name","Age","Sex"]].head()

                                    Name   Age     Sex
7         Palsson, Master. Gosta Leonard   2.0    male
9    Nasser, Mrs. Nicholas (Adele Achem)  14.0  female
10       Sandstrom, Miss. Marguerite Rut   4.0  female
14  Vestrom, Miss. Hulda Amanda Adolfina  14.0  female
16                  Rice, Master. Eugene   2.0    male

### Filtering with Multiple Conditions
#### "AND" conditions: `&`
Example: female passengers in first class

Important rule: Each condition must be inside parentheses.

In [11]:
first_class_women = df[
    (df["Sex"] == "female") & (df["Pclass"] == 1)
]

first_class_women[["Name","Sex","Pclass"]].head()

                                                 Name     Sex  Pclass
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female       1
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female       1
11                           Bonnell, Miss. Elizabeth  female       1
31     Spencer, Mrs. William Augustus (Marie Eugenie)  female       1
52           Harper, Mrs. Henry Sleeper (Myna Haxtun)  female       1

#### "OR" conditions: `|`

Example: passengers who are children OR elderly

In [12]:
young_or_old = df[
    (df["Age"] < 18) | (df["Age"] > 60)
]

young_or_old[["Name","Age"]].head()

                                    Name   Age
7         Palsson, Master. Gosta Leonard   2.0
9    Nasser, Mrs. Nicholas (Adele Achem)  14.0
10       Sandstrom, Miss. Marguerite Rut   4.0
14  Vestrom, Miss. Hulda Amanda Adolfina  14.0
16                  Rice, Master. Eugene   2.0

### Negation of conditions

Example: Select passengers who are NOT children.

Important Note: the difference between `df[df["Age"] >= 18)]` and `df[~(df["Age"] < 18)]` is that the former only select passengers whose age is equal to or greater than 18, but the latter will also select NaN values.

In [34]:
not_children = df[~(df["Age"] < 18)]

not_children[["Name","Age"]].head()

                                                Name   Age
0                            Braund, Mr. Owen Harris  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                             Heikkinen, Miss. Laina  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                           Allen, Mr. William Henry  35.0

### Practical Examples
#### Example #1

Find third-class adult male passengers with very low fare.

In [35]:
low_fare_passengers = df[
    (df["Pclass"] == 3) &
    (df["Sex"] == "male") &
    (df["Fare"] < 10) &
    (~(df["Age"] < 18)) # You can use df['Age'] >= 18 but here is just a nice exercise
]

low_fare_passengers[["Name","Pclass","Sex", "Age", "Fare"]].head()

                              Name  Pclass   Sex   Age    Fare
0          Braund, Mr. Owen Harris       3  male  22.0  7.2500
4         Allen, Mr. William Henry       3  male  35.0  8.0500
5                 Moran, Mr. James       3  male   NaN  8.4583
12  Saundercock, Mr. William Henry       3  male  20.0  8.0500
26         Emir, Mr. Farred Chehab       3  male   NaN  7.2250

#### Example #2
Check survival rate of children vs adults.

In [42]:
children = df[df["Age"] < 18]
adults = df[df["Age"] >= 18]

print(f"Children survival rate: {children['Survived'].mean():.2f}")
print(f"Adult survival rate: {adults['Survived'].mean():.2f}")

Children survival rate: 0.54
Adult survival rate: 0.38

## Advanced Filtering