# Groupby

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("./data/IMDB Top 250 Movies.csv")

# let's clean the data type
numeric_columns = ["budget",'box_office']

for col in numeric_columns:
    df[col] = df[col].apply(pd.to_numeric, errors='coerce')

df

,rank,name,year,rating,genre,certificate,run_time,tagline,budget,box_office,casts,directors,writers
0,1,The Shawshank Redemption,1994,9.3,Drama,R,2h 22m,Fear can hold you prisoner. Hope can set you f...,25000000.0,2.888450e+07,"Tim Robbins,Morgan Freeman,Bob Gunton,William ...",Frank Darabont,"Stephen King,Frank Darabont"
1,2,The Godfather,1972,9.2,"Crime,Drama",R,2h 55m,An offer you can't refuse.,6000000.0,2.503418e+08,"Marlon Brando,Al Pacino,James Caan,Diane Keato...",Francis Ford Coppola,"Mario Puzo,Francis Ford Coppola"
2,3,The Dark Knight,2008,9.0,"Action,Crime,Drama",PG-13,2h 32m,Why So Serious?,185000000.0,1.006234e+09,"Christian Bale,Heath Ledger,Aaron Eckhart,Mich...",Christopher Nolan,"Jonathan Nolan,Christopher Nolan,David S. Goyer"
3,4,The Godfather Part II,1974,9.0,"Crime,Drama",R,3h 22m,All the power on earth can't change destiny.,13000000.0,4.796192e+07,"Al Pacino,Robert De Niro,Robert Duvall,Diane K...",Francis Ford Coppola,"Francis Ford Coppola,Mario Puzo"
4,5,12 Angry Men,1957,9.0,"Crime,Drama",Approved,1h 36m,Life Is In Their Hands -- Death Is On Their Mi...,350000.0,9.550000e+02,"Henry Fonda,Lee J. Cobb,Martin Balsam,John Fie...",Sidney Lumet,Reginald Rose
...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,246,The Help,2011,8.1,Drama,PG-13,2h 26m,Change begins with a whisper.,25000000.0,2.166391e+08,"Viola Davis,Emma Stone,Octavia Spencer,Bryce D...",Tate Taylor,"Tate Taylor,Kathryn Stockett"
246,247,Dersu Uzala,1975,8.2,"Adventure,Biography,Drama",G,2h 22m,There is man and beast at nature's mercy. Ther...,4000000.0,1.448000e+04,"Maksim Munzuk,Yuriy Solomin,Mikhail Bychkov,Vl...",Akira Kurosawa,"Akira Kurosawa,Yuriy Nagibin,Vladimir Arsenev"
247,248,Aladdin,1992,8.0,"Animation,Adventure,Comedy",G,1h 30m,Wish granted! (DVD re-release),NaN,NaN,"Scott Weinger,Robin Williams,Linda Larkin,Jona...","Ron Clements,John Musker","Ron Clements,John Musker,Ted Elliott"
248,249,Gandhi,1982,8.0,"Biography,Drama,History",PG,3h 11m,His Triumph Changed The World Forever.,22000000.0,5.276789e+07,"Ben Kingsley,John Gielgud,Rohini Hattangadi,Ro...",Richard Attenborough,John Briley
249,250,Dances with Wolves,1990,8.0,"Adventure,Drama,Western",PG-13,3h 1m,Inside everyone is a frontier waiting to be di...,22000000.0,4.242088e+08,"Kevin Costner,Mary McDonnell,Graham Greene,Rod...",Kevin Costner,Michael Blake

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   rank         250 non-null    int64
 1   name         250 non-null    object
 2   year         250 non-null    int64
 3   rating       250 non-null    float64
 4   genre        250 non-null    object
 5   certificate  250 non-null    object
 6   run_time     250 non-null    object
 7   tagline      250 non-null    object
 8   budget       206 non-null    float64
 9   box_office   217 non-null    float64
 10  casts        250 non-null    object
 11  directors    250 non-null    object
 12  writers      250 non-null    object
dtypes: float64(3), int64(2), object(8)
memory usage: 25.5+ KB

## Basic group by

Average rating by genre

In [5]:
genre_rating = df.groupby("genre")["rating"].count()

genre_rating.sort_values(ascending=False)

genre
Drama                         19
Crime,Drama                   14
Animation,Adventure,Comedy    10
Biography,Drama,History        9
Crime,Drama,Mystery            9
                              ..
Crime,Mystery,Thriller         1
Crime,Sci-Fi                   1
Adventure,Comedy,Sci-Fi        1
Adventure,Comedy,Fantasy       1
Adventure,Comedy,Drama         1
Name: rating, Length: 104, dtype: int64

Actually, we can see that one movie might have multiple genres. If we wanted to group by individual genre, we could do `.explode` and then `.groupby`

In [6]:
df_exploded_by_genre = df.assign(
    genre_list = lambda df: df["genre"].str.split(",")
).explode('genre_list')

df_exploded_by_genre.head()

,rank,name,year,rating,genre,certificate,run_time,tagline,budget,box_office,casts,directors,writers,genre_list
0,1,The Shawshank Redemption,1994,9.3,Drama,R,2h 22m,Fear can hold you prisoner. Hope can set you f...,25000000.0,2.888450e+07,"Tim Robbins,Morgan Freeman,Bob Gunton,William ...",Frank Darabont,"Stephen King,Frank Darabont",Drama
1,2,The Godfather,1972,9.2,"Crime,Drama",R,2h 55m,An offer you can't refuse.,6000000.0,2.503418e+08,"Marlon Brando,Al Pacino,James Caan,Diane Keato...",Francis Ford Coppola,"Mario Puzo,Francis Ford Coppola",Crime
1,2,The Godfather,1972,9.2,"Crime,Drama",R,2h 55m,An offer you can't refuse.,6000000.0,2.503418e+08,"Marlon Brando,Al Pacino,James Caan,Diane Keato...",Francis Ford Coppola,"Mario Puzo,Francis Ford Coppola",Drama
2,3,The Dark Knight,2008,9.0,"Action,Crime,Drama",PG-13,2h 32m,Why So Serious?,185000000.0,1.006234e+09,"Christian Bale,Heath Ledger,Aaron Eckhart,Mich...",Christopher Nolan,"Jonathan Nolan,Christopher Nolan,David S. Goyer",Action
2,3,The Dark Knight,2008,9.0,"Action,Crime,Drama",PG-13,2h 32m,Why So Serious?,185000000.0,1.006234e+09,"Christian Bale,Heath Ledger,Aaron Eckhart,Mich...",Christopher Nolan,"Jonathan Nolan,Christopher Nolan,David S. Goyer",Crime

In [7]:
# compute individual genre's average rating

genre_rating = df_exploded_by_genre.groupby(by='genre_list')['rating'].mean().reset_index().rename(columns={"genre_list": "genre", "rating":"mean_rating"})

genre_rating.sort_values(by='mean_rating',ascending=False)

        genre  mean_rating
12      Music     8.400000
5       Crime     8.360784
16     Sci-Fi     8.360000
0      Action     8.350000
11     Horror     8.340000
20    Western     8.328571
14    Mystery     8.325806
6       Drama     8.320339
8     Fantasy     8.307143
1   Adventure     8.300000
13    Musical     8.300000
15    Romance     8.295652
19        War     8.291304
10    History     8.270000
18   Thriller     8.256667
2   Animation     8.256522
7      Family     8.253846
3   Biography     8.248276
4      Comedy     8.231111
9   Film-Noir     8.225000
17      Sport     8.160000

## Count movies by Genre or Year

In [ ]:
genre_count = df_exploded_by_genre.groupby("genre_list")["name"].count().reset_index().rename(columns={"name":"movie_count"})

genre_count.sort_values(by="movie_count", ascending=False)

In [8]:
yearly_count = df.groupby("year")["name"].count().reset_index().rename(columns={"name":"movie_count"})

yearly_count

    year  movie_count
0   1921            1
1   1924            1
2   1925            1
3   1926            1
4   1927            1
..   ...          ...
81  2018            4
82  2019            6
83  2020            2
84  2021            2
85  2022            1

[86 rows x 2 columns]

In [ ]:
sns.lineplot(data=yearly_count, x="year", y="movie_count")

## Group by multiple columns

In [11]:
yearly_movies_by_genre = df_exploded_by_genre.groupby(['year', 'genre_list'], as_index=False)['name'].count().rename(columns={"name":"movie_count","genre_list":"genre"})

yearly_movies_by_genre

     year    genre  movie_count
0    1921   Comedy            1
1    1921    Drama            1
2    1921   Family            1
3    1924   Action            1
4    1924   Comedy            1
..    ...      ...          ...
444  2021    Drama            1
445  2021  Fantasy            1
446  2021  Mystery            1
447  2022   Action            1
448  2022    Drama            1

[449 rows x 3 columns]

## Multiple aggregations

### Use a dictionary

- One groupby with multiple metrics
- Output becomes multi-level columns

In [13]:
genre_summary = df_exploded_by_genre.groupby("genre_list").agg(
    {"rating": ["mean", "max"],
    "box_office": "mean"}
)

genre_summary

              rating         box_office
                mean  max          mean
genre_list
Action      8.350000  9.0  5.441123e+08
Adventure   8.300000  9.0  5.314875e+08
Animation   8.256522  8.6  5.233542e+08
Biography   8.248276  9.0  1.524409e+08
Comedy      8.231111  8.6  2.440025e+08
Crime       8.360784  9.2  1.448480e+08
Drama       8.320339  9.3  1.849390e+08
Family      8.253846  8.6  2.969566e+08
Fantasy     8.307143  8.7  4.758143e+08
Film-Noir   8.225000  8.4  4.033765e+05
History     8.270000  9.0  1.353418e+08
Horror      8.340000  8.5  1.293226e+08
Music       8.400000  8.5  5.543280e+07
Musical     8.300000  8.3  2.000288e+06
Mystery     8.325806  8.8  7.982119e+07
Romance     8.295652  8.8  9.620699e+07
Sci-Fi      8.360000  8.8  3.984243e+08
Sport       8.160000  8.2  9.518127e+07
Thriller    8.256667  8.6  1.668086e+08
War         8.291304  8.6  9.984385e+07
Western     8.328571  8.8  1.514506e+08

In [14]:
# It generates multi-level index
genre_summary.columns

MultiIndex([(    'rating', 'mean'),
            (    'rating',  'max'),
            ('box_office', 'mean')],
           )

In [15]:
# I prefer converting them to one-level index
genre_summary.columns = ["_".join(i) for i in genre_summary.columns]
genre_summary

            rating_mean  rating_max  box_office_mean
genre_list
Action         8.350000         9.0     5.441123e+08
Adventure      8.300000         9.0     5.314875e+08
Animation      8.256522         8.6     5.233542e+08
Biography      8.248276         9.0     1.524409e+08
Comedy         8.231111         8.6     2.440025e+08
Crime          8.360784         9.2     1.448480e+08
Drama          8.320339         9.3     1.849390e+08
Family         8.253846         8.6     2.969566e+08
Fantasy        8.307143         8.7     4.758143e+08
Film-Noir      8.225000         8.4     4.033765e+05
History        8.270000         9.0     1.353418e+08
Horror         8.340000         8.5     1.293226e+08
Music          8.400000         8.5     5.543280e+07
Musical        8.300000         8.3     2.000288e+06
Mystery        8.325806         8.8     7.982119e+07
Romance        8.295652         8.8     9.620699e+07
Sci-Fi         8.360000         8.8     3.984243e+08
Sport          8.160000         8.2     9.518127e+07
Thriller       8.256667         8.6     1.668086e+08
War            8.291304         8.6     9.984385e+07
Western        8.328571         8.8     1.514506e+08

In [16]:
genre_summary.columns

Index(['rating_mean', 'rating_max', 'box_office_mean'], dtype='object')

### Custom naming
#### Custom naming with tuples

In [17]:
genre_summary = df_exploded_by_genre.groupby("genre_list").agg(
    rating_mean=("rating", 'mean'),
    rating_max=("rating", "max"),
    box_office_mean=("box_office", lambda x: x.mean()+1) # you can also use custom functions
).rename(columns={"genre_list":"genre"})

genre_summary

            rating_mean  rating_max  box_office_mean
genre_list
Action         8.350000         9.0     5.441123e+08
Adventure      8.300000         9.0     5.314875e+08
Animation      8.256522         8.6     5.233542e+08
Biography      8.248276         9.0     1.524409e+08
Comedy         8.231111         8.6     2.440025e+08
Crime          8.360784         9.2     1.448480e+08
Drama          8.320339         9.3     1.849390e+08
Family         8.253846         8.6     2.969566e+08
Fantasy        8.307143         8.7     4.758143e+08
Film-Noir      8.225000         8.4     4.033775e+05
History        8.270000         9.0     1.353418e+08
Horror         8.340000         8.5     1.293226e+08
Music          8.400000         8.5     5.543280e+07
Musical        8.300000         8.3     2.000289e+06
Mystery        8.325806         8.8     7.982119e+07
Romance        8.295652         8.8     9.620699e+07
Sci-Fi         8.360000         8.8     3.984243e+08
Sport          8.160000         8.2     9.518127e+07
Thriller       8.256667         8.6     1.668086e+08
War            8.291304         8.6     9.984385e+07
Western        8.328571         8.8     1.514506e+08

#### Custom naming with `pd.NamedAgg()`
This is a very powerful method that enables highly customizable aggregation functions

In [18]:
genre_summary = df_exploded_by_genre.groupby("genre_list", as_index=False).agg(
    rating_mean = ('rating', 'mean'),
    rating_max = pd.NamedAgg(column='rating', aggfunc='max'),
    box_office = pd.NamedAgg(column='box_office', aggfunc=lambda x: x.mean()),
    average_run_time = pd.NamedAgg(column='run_time', aggfunc=lambda x: pd.to_timedelta(x, unit='m', errors='coerce').mean().total_seconds()/60)
).rename(columns={"genre_list":"genre"})

genre_summary

        genre  rating_mean  rating_max    box_office  average_run_time
0      Action     8.350000         9.0  5.441123e+08        133.820000
1   Adventure     8.300000         9.0  5.314875e+08        130.116667
2   Animation     8.256522         8.6  5.233542e+08        100.956522
3   Biography     8.248276         9.0  1.524409e+08        147.068966
4      Comedy     8.231111         8.6  2.440025e+08        105.600000
5       Crime     8.360784         9.2  1.448480e+08        131.784314
6       Drama     8.320339         9.3  1.849390e+08        134.818182
7      Family     8.253846         8.6  2.969566e+08        114.538462
8     Fantasy     8.307143         8.7  4.758143e+08        123.571429
9   Film-Noir     8.225000         8.4  4.033765e+05        110.000000
10    History     8.270000         9.0  1.353418e+08        156.000000
11     Horror     8.340000         8.5  1.293226e+08        120.600000
12      Music     8.400000         8.5  5.543280e+07        134.250000
13    Musical     8.300000         8.3  2.000288e+06        103.000000
14    Mystery     8.325806         8.8  7.982119e+07        124.612903
15    Romance     8.295652         8.8  9.620699e+07        118.478261
16     Sci-Fi     8.360000         8.8  3.984243e+08        131.700000
17      Sport     8.160000         8.2  9.518127e+07        122.000000
18   Thriller     8.256667         8.6  1.668086e+08        121.033333
19        War     8.291304         8.6  9.984385e+07        140.045455
20    Western     8.328571         8.8  1.514506e+08        153.857143

## Find Top Movie per Genre

### Method 1:

In [19]:
top_movies = df_exploded_by_genre.sort_values(by='rating', ascending=False).groupby("genre_list", as_index=False).first()

top_movies[["genre_list", "name", "rating"]]

   genre_list                                            name  rating
0      Action   The Lord of the Rings: The Return of the King     9.0
1   Adventure   The Lord of the Rings: The Return of the King     9.0
2   Animation                                   Spirited Away     8.6
3   Biography                                Schindler's List     9.0
4      Comedy                               Life Is Beautiful     8.6
5       Crime                                   The Godfather     9.2
6       Drama                        The Shawshank Redemption     9.3
7      Family                                   Spirited Away     8.6
8     Fantasy  Star Wars: Episode V - The Empire Strikes Back     8.7
9   Film-Noir                                    Sunset Blvd.     8.4
10    History                                Schindler's List     9.0
11     Horror                                           Alien     8.5
12      Music                                        Whiplash     8.5
13    Musical                             Singin' in the Rain     8.3
14    Mystery                                        Jai Bhim     8.8
15    Romance                                    Forrest Gump     8.8
16     Sci-Fi                                       Inception     8.8
17      Sport                                     Raging Bull     8.2
18   Thriller                        The Silence of the Lambs     8.6
19        War                             Saving Private Ryan     8.6
20    Western                  The Good, the Bad and the Ugly     8.8

### Method 2

In [20]:
top_movies = df_exploded_by_genre.reset_index().iloc[df_exploded_by_genre.reset_index().groupby("genre_list")['rating'].idxmax()]

top_movies[["genre_list", "name", "rating"]]

    genre_list                                            name  rating
3       Action                                 The Dark Knight     9.0
14   Adventure   The Lord of the Rings: The Return of the King     9.0
73   Animation                                   Spirited Away     8.6
10   Biography                                Schindler's List     9.0
59      Comedy                               Life Is Beautiful     8.6
1        Crime                                   The Godfather     9.2
0        Drama                        The Shawshank Redemption     9.3
47      Family                           It's a Wonderful Life     8.6
34     Fantasy  Star Wars: Episode V - The Empire Strikes Back     8.7
147  Film-Noir                                    Sunset Blvd.     8.4
12     History                                Schindler's List     9.0
79      Horror                                          Psycho     8.5
78       Music                                     The Pianist     8.5
211    Musical                             Singin' in the Rain     8.3
586    Mystery                                        Jai Bhim     8.8
24     Romance                                    Forrest Gump     8.8
31      Sci-Fi                                       Inception     8.8
389      Sport                                     Raging Bull     8.2
51    Thriller                        The Silence of the Lambs     8.6
55         War                             Saving Private Ryan     8.6
22     Western                  The Good, the Bad and the Ugly     8.8

## Groupby and Transform

### Example 1: compute the proportion of box office of each movie in each genre

In [21]:
df_exploded_by_genre['box_office_pct_in_genre'] = df_exploded_by_genre.groupby("genre_list")['box_office'].transform(lambda x: x*100/x.sum())

df_exploded_by_genre[['name','genre_list','box_office','box_office_pct_in_genre']]

,name,genre_list,box_office,box_office_pct_in_genre
0,The Shawshank Redemption,Drama,2.888450e+07,0.103433
1,The Godfather,Crime,2.503418e+08,3.840683
1,The Godfather,Drama,2.503418e+08,0.896454
2,The Dark Knight,Action,1.006234e+09,4.109585
2,The Dark Knight,Crime,1.006234e+09,15.437399
...,...,...,...,...
248,Gandhi,Drama,5.276789e+07,0.188958
248,Gandhi,History,5.276789e+07,4.873577
249,Dances with Wolves,Adventure,4.242088e+08,1.425275
249,Dances with Wolves,Drama,4.242088e+08,1.519058
249,Dances with Wolves,Western,4.242088e+08,40.013892

We can further compute the diversity or uncertainty index (HHI or Shannon Entropy) in each genre in terms of box office, using `.groupby()`

_Herfindahl-Hirschman index (HHI)_ is a measure of market concentration calculated by summing the squares of the percentage market shares of all firms in an industry.

Variations of HHI:
- Basic HHI (or Simpson Index): $\lambda = \sum_{i=1}^{n} s_i^2$
- Inverse HHI (or inverse Simpson index): $\frac{1}{\lambda} = \frac{1}{\sum_{i=1}^{n} s_i^2}$
- Gini-Simpson Index (or Gini's diversity index in machine learning): $1-\lambda = 1- \sum_{i=1}^{n} s_i^2$
    - The higher it is, the more diverse the system is

In [22]:
genre_diversity = df_exploded_by_genre.groupby("genre_list", as_index=False).agg(
    box_office_gini_diversity = pd.NamedAgg(column='box_office_pct_in_genre', aggfunc=lambda x: 1-((x/100)**2).sum()),
)

genre_diversity

   genre_list  box_office_gini_diversity
0      Action                   0.950851
1   Adventure                   0.962657
2   Animation                   0.922093
3   Biography                   0.926607
4      Comedy                   0.933072
5       Crime                   0.924981
6       Drama                   0.970813
7      Family                   0.680329
8     Fantasy                   0.813510
9   Film-Noir                   0.385496
10    History                   0.804211
11     Horror                   0.498453
12      Music                   0.601982
13    Musical                   0.000000
14    Mystery                   0.834385
15    Romance                   0.733879
16     Sci-Fi                   0.873803
17      Sport                   0.573478
18   Thriller                   0.861783
19        War                   0.843257
20    Western                   0.655009

### Example 2: Compute z-score of ratings

A Z-score (standard score) measures how many standard deviations a data point (x) is above or below the population mean (μ).

$z=\frac{x-\mu}{\sigma}$

where $\sigma$ represents the standard deviation.

In [24]:

df_exploded_by_genre['rating_z_score'] = df_exploded_by_genre.groupby("genre_list")['rating'].transform(lambda x: (x-x.mean())/x.std())

df_exploded_by_genre[['name','genre_list','rating','rating_z_score']]

                         name genre_list  rating  rating_z_score
0    The Shawshank Redemption      Drama     9.3        4.021064
1               The Godfather      Crime     9.2        2.951777
1               The Godfather      Drama     9.2        3.610609
2             The Dark Knight     Action     9.0        2.598939
2             The Dark Knight      Crime     9.0        2.248316
..                        ...        ...     ...             ...
248                    Gandhi      Drama     8.0       -1.314846
248                    Gandhi    History     8.0       -0.940970
249        Dances with Wolves  Adventure     8.0       -1.296295
249        Dances with Wolves      Drama     8.0       -1.314846
249        Dances with Wolves    Western     8.0       -1.250419

[625 rows x 4 columns]

## Group by and sample

In [27]:
sample_by_genre = df_exploded_by_genre.groupby("genre_list", as_index=False).sample(2, replace=True)

sample_by_genre[['genre_list','name']]

    genre_list                                               name
230     Action  Pirates of the Caribbean: The Curse of the Bla...
117     Action                                           Die Hard
226  Adventure                                    The Incredibles
6    Adventure      The Lord of the Rings: The Return of the King
112  Animation                                                 Up
171  Animation                                 My Neighbor Totoro
124  Biography                                             Dangal
31   Biography                                        The Pianist
223     Comedy                                      Groundhog Day
195     Comedy                                         Wild Tales
91       Crime                                     Reservoir Dogs
184      Crime                           The Grand Budapest Hotel
58       Drama                                       Sunset Blvd.
1        Drama                                      The Godfather
121     Family                                Like Stars on Earth
56      Family                                             WALL·E
149    Fantasy                            Spider-Man: No Way Home
136    Fantasy                                    Pan's Labyrinth
187  Film-Noir                                      The Third Man
58   Film-Noir                                       Sunset Blvd.
123    History                                           Downfall
207    History                         The Passion of Joan of Arc
60      Horror                                        The Shining
50      Horror                                              Alien
41       Music                                           Whiplash
41       Music                                           Whiplash
83     Musical                                Singin' in the Rain
83     Musical                                Singin' in the Rain
39     Mystery                                 The Usual Suspects
94     Mystery                                       Citizen Kane
46     Romance                                       Modern Times
25     Romance                                  Life Is Beautiful
28      Sci-Fi                         Terminator 2: Judgment Day
143     Sci-Fi                                      Jurassic Park
156      Sport                                        Raging Bull
168      Sport                                            Warrior
74    Thriller                                              Joker
48    Thriller                                        Rear Window
92         War                                       Come and See
227        War                                 To Be or Not to Be
139    Western                                         Unforgiven
249    Western                                 Dances with Wolves