# Rename Axis and Columns

In [6]:
import pandas as pd

df = pd.DataFrame({
    "user_id": [101, 102, 103],
    "date": ["2026-02-01", "2026-02-01", "2026-02-01"],
    "steps": [8500, 12000, 4300],
    "sleep_hours": [7.5, 6.0, 8.2],
    "workout_type": ["Cardio", "Strength", "None"]
})

df

   user_id        date  steps  sleep_hours workout_type
0      101  2026-02-01   8500          7.5       Cardio
1      102  2026-02-01  12000          6.0     Strength
2      103  2026-02-01   4300          8.2         None

In [2]:
# user_id is no longer one of the columns
print(df.columns)

# user_id now is the index of the dataframe
print(df.index)

Index(['user_id', 'date', 'steps', 'sleep_hours', 'workout_type'], dtype='object')
RangeIndex(start=0, stop=3, step=1)

## Renaming Columns
Rename Specific Columns (Best Practice)

- Safe and explicit.
- Doesn’t break column order.

In [5]:
df.rename(columns={
    "sleep_hours": "sleep_h",
    "workout_type": "exercise_type"
}, inplace=True)
print(df)

   user_id        date  steps  sleep_h exercise_type
0      101  2026-02-01   8500      7.5        Cardio
1      102  2026-02-01  12000      6.0      Strength
2      103  2026-02-01   4300      8.2          None

## Rename All Columns at Once
Warning: Must match number of columns exactly.

In [7]:

df.columns = ["id", "date", "daily_steps", "sleep_h", "exercise_type"]
df

    id        date  daily_steps  sleep_h exercise_type
0  101  2026-02-01         8500      7.5        Cardio
1  102  2026-02-01        12000      6.0      Strength
2  103  2026-02-01         4300      8.2          None

## Setting Index
Example: Use `id` as Index

In [ ]:
df = df.set_index("id")
df

## Rename index and axis
Two ways of doing it

In [ ]:
# first way, use df.index.rename()
df.index.rename("user_id", inplace=True)
df

In [ ]:
# second way, assign a new value to df.index.name
df.index.name = 'id'
df

rename column axis

In [ ]:
print("Before rename column axis, checking column information")
print(df.columns)

print("\nLet's rename the column axis")
df.columns.name = "health_metrics"
print(df.columns)

## Set Multi-Index
Track by user and date:

- Now you have a hierarchical index.
- This is common in panel/time-series data.
- Each user can have multiple dates.

In [ ]:
df = df.reset_index()
df = df.set_index(["id", "date"])
df

In [ ]:
df.index

After setting multi-index: Index affects how we select data. Index structure changes how we think about data.

In [ ]:
df.loc[(101, "2026-02-01")]

## Reset Index
- Flattens the table.
- Needed before merging or exporting.

In [ ]:
df = df.reset_index()
df

## Renaming Index Labels

In [ ]:
df.set_index('user_id', inplace=True)
df

In [ ]:
df.rename(index={101: "User_A"})